<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除",
                        ],
                        "menu":"员工表管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"员工表管理"
            }
			,
			{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除",
                            "验收",
                        ],
                        "menu":"项目信息模块管理",
                        "menuJump":"列表",
                        "tableName":"xiangmu"
                    }
                ],
                "menu":"项目信息模块管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除",
                        ],
                        "menu":"部门管理",
                        "menuJump":"列表",
                        "tableName":"dictionary_bumen"
                    }
                ],
                "menu":"部门管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除",
                        ],
                        "menu":"任务类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionary_rwleix"
                    }
                ],
                "menu":"任务类型管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"费用报销单管理",
                        "menuJump":"列表",
                        "tableName":"feiyongbaoxiao"
                    }
                ],
                "menu":"费用报销单管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除",
                        ],
                        "menu":"项目分配管理",
                        "menuJump":"列表",
                        "tableName":"fenpei"
                    }
                ],
                "menu":"项目分配管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除",
                        ],
                        "menu":"合同模块管理",
                        "menuJump":"列表",
                        "tableName":"hetong"
                    }
                ],
                "menu":"合同模块管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除",
                        ],
                        "menu":"客户模块管理",
                        "menuJump":"列表",
                        "tableName":"kehu"
                    }
                ],
                "menu":"客户模块管理"
            },{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除",
                        ],
                        "menu":"任务管理",
                        "menuJump":"列表",
                        "tableName":"renwu"
                    }
                ],
                "menu":"任务管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
        "backMenu":[
			{
                "child":[
                    {
                        "buttons":[
                            "查看",
                        ],
                        "menu":"部门管理",
                        "menuJump":"列表",
                        "tableName":"dictionary_bumen"
                    }
                ],
                "menu":"部门管理"
            },
			{
                "child":[
                    {
                        "buttons":[
                            "查看",
                        ],
                        "menu":"项目信息模块管理",
                        "menuJump":"列表",
                        "tableName":"xiangmu"
                    }
                ],
                "menu":"项目信息模块管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                        ],
                        "menu":"任务类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionary_rwleix"
                    }
                ],
                "menu":"任务类型管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                        ],
                        "menu":"费用报销单管理",
                        "menuJump":"列表",
                        "tableName":"feiyongbaoxiao"
                    }
                ],
                "menu":"费用报销单管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                        ],
                        "menu":"项目分配管理",
                        "menuJump":"列表",
                        "tableName":"fenpei"
                    }
                ],
                "menu":"项目分配管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                        ],
                        "menu":"合同模块管理",
                        "menuJump":"列表",
                        "tableName":"hetong"
                    }
                ],
                "menu":"合同模块管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                        ],
                        "menu":"客户模块管理",
                        "menuJump":"列表",
                        "tableName":"kehu"
                    }
                ],
                "menu":"客户模块管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                        ],
                        "menu":"任务管理",
                        "menuJump":"列表",
                        "tableName":"renwu"
                    }
                ],
                "menu":"任务管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"员工",
        "tableName":"yonghu"
    }
];

var hasMessage = '';
